### ISSUE TITLE
Why hasn't voting changed?

### ISSUE THREAD

**Issue by dsernst** [voteliquid/blog#11]
First draft by @henryw4k:

> # Why hasn't voting changed?
> 
> American voting goes back to 1776.
> 
> Back then, everyone was excited about voting. Excited about participating (if they were allowed to...). With only 13 states, and far less people, they could see the impact around them.
> 
> ![picture that shows back in the day: clothing, log cabin, or something]
> 
> Voting today hasn't changed much. We still go to a polling center. Pony Express is now USPS. People still tally up all the votes by hand.
> 
> Imagine we still used the transportation technology from 1776: we'd be riding around on horses instead of airplanes and Teslas.
> 
> Money is another technology where it's become much easier. We don't bring cash to the bank each time we get paid. We have checks and ATM. We can manage our bank accounts through a website or on our phones, and when we go to a store we can pay with a plastic card.
> 
> If it's possible to manage our life savings through computers, can't we digitize our voting?
> 
> Why do we have to go to the polls when we have smartphones?
> 
> Why do we have to mail it in?
> 
> Why do we have to wait to learn the results?
> 
> Why do we spend hundreds of millions of taxpayer dollars to run elections?
> 
> Liquid democracy offers a solution: [learn more]().

**Comment by dsernst** [comment]
@henryw4k: here's an idea for an image, what do you think?

![1776](http://i.onionstatic.com/avclub/3725/69/16x9/960.jpg)

**Comment by henryw4k** [comment]
YES!! lol

**Comment by dsernst** [comment]
@henryw4k 👍 😄 Do you want to do any more edits before this is published?

**Comment by dsernst** [comment]
Closed in favor of PR https://github.com/liquidvote/blog/pull/23
