### ISSUE TITLE
Add inline newsletter call-to-action signup

### ISSUE THREAD

**Issue by dsernst** [voteliquid/blog#17]
Coinbase sets a good example:

<img width="1651" alt="screen shot 2016-10-09 at 12 38 34 pm" src="https://cloud.githubusercontent.com/assets/6340841/19223154/5de88b36-8e1d-11e6-8a29-9c28ed5d933e.png">

^ from their front page

---

---

<img width="1662" alt="screen shot 2016-10-09 at 12 38 48 pm" src="https://cloud.githubusercontent.com/assets/6340841/19223156/659f6f7a-8e1d-11e6-9271-311aa64f1073.png">

^ footer of every post

**Comment by dsernst** [comment]
Love the message on this one from [dcurt.is](http://dcurt.is)

<img width="653" alt="screen shot 2016-10-11 at 10 40 36 am" src="https://cloud.githubusercontent.com/assets/6340841/19281464/42d80870-8f9f-11e6-9932-45a8266385b8.png">

**Comment by jaredscheib** [comment]
We've done the frontend for this: https://github.com/liquidvote/blog/commit/2df551dd25d900bbaed0d48dc527bb9a3e7ddf90

We still need:
- [x] api
- [x] send to api
- [x] show success
- [x] maybe some error handling
- [ ] maybe some client-side validation

**Comment by dsernst** [comment]
Sends to API as of https://github.com/liquidvote/blog/commit/cdfa961188445a6dfa887e96de0dcf67c9994884

**Comment by dsernst** [comment]
Added success message in https://github.com/liquidvote/blog/commit/d05d99b9d3e4475b25c91ff43f8bcf88e3f41582:

<img width="711" alt="screen shot 2016-10-15 at 12 37 47 am" src="https://cloud.githubusercontent.com/assets/6340841/19408358/c2735d96-926f-11e6-842a-adef2f9460b0.png">

**Comment by dsernst** [comment]
Right now there's no feedback if there's an error

**Comment by dsernst** [comment]
Added error handling:
- If the email is a duplicate (status code `409`), show the `Subscribed` confirmation anyway.
- If the email is invalid (status code `400`), add a 1px red border around the input field.
